config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats do 
    resources :toys, only: [:index, :new]
  end

  resources :toys, only: [:create, :update, :destroy, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show] do 
    resource :counter, only: [:update]
  end

  root to: redirect("/cats")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  gender     :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Cat < ApplicationRecord
    GENDER = ["male", "female"]

    validates :name, presence: true
    validates :gender, presence: true, inclusion: GENDER
    validate :valid_name_length?

    has_many :toys

    
    private

    def valid_name_length?
        if self.name.nil? || self.name.length < 2
            errors.add(:name, "is too short (minimum is 2 characters)")
        end
    end
end

app/models/test_model.rb
class TestModel < ApplicationRecord
end

app/models/toy.rb
# == Schema Information
#
# Table name: toys
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  style      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cat_id     :integer
#
class Toy < ApplicationRecord
    STYLES = ["ball", "string", "mouse", "laser"]

    validates :style, presence: true
    validates :name, presence: true, length: { minimum: 2 }
    validates :style, inclusion: STYLES

    belongs_to :cat
end

app/models/user.rb
class User < ApplicationRecord
    attr_reader :password

    validates :password_digest, presence: { message: 'Password can\'t be blank!' }
    validates :username, presence: true, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true }
    validates :session_token, presence: true
    after_initialize :ensure_session_token

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def reset_session_token!
        self.session_token = self.class.generate_session_token
        self.save!
        self.session_token
    end
    
    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end

    private

    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # skip_before_action :verify_authenticity_token

    #Used as part of CSRF protection
    protect_from_forgery with: :exception

    # This enables :current_user to be used throughout any view.
    helper_method :current_user

    def login!(user)
        @current_user = user
        session[:session_token] = user.session_token
    end

    def current_user
        return nil if session[:session_token].nil?
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logout!
        current_user.try(:reset_session_token!)
        session[:session_token] = nil
    end

    def require_current_user!
        redirect_to new_session_path if current_user.nil?
    end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
    before_action :require_current_user!, only: [:create, :new, :edit, :update, :destroy]

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(self.params[:id])
        render :show
    end

    def create
        @cat = Cat.new(cats_params)
        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new # This :new means the new.html.erb form. NOT THE NEW METHOD BELOW!
        end
    end

    def new
        # /cats/new
        # show a form to create a new object
        @cat = Cat.new #this is just a dummy object 是为了在最开始没有填写的时候不报错。否则没有object但是用object.name会报错
        render :new
    end

    def edit 
        # /cats/id/edit
        # show a form to edit an existing object
        @cat = Cat.find(params[:id])
        render :edit
    end

    def update
        @cat = Cat.find(params[:id])
        # @theurl = cat_url(@cat)
        if @cat.update(cats_params)
            redirect_to cat_url(@cat)
        else
            render :edit
        end
    end

    def destroy
        cat = Cat.find(params[:id])
        cat.destroy
        redirect_to cats_url
    end

    private

    def cats_params
        self.params[:cat].permit(:name, :gender)
    end


end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
    def update
        current_user.counter = params[:user][:user_id][:counter]
        current_user.save!
        redirect_to user_url(current_user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        # @user = User.new
        render :new
    end

    def create 
        user = User.find_by_credentials(params[:user][:username], params[:user][:password])

        if user.nil?
            # render json: "Credentials were wrong."
            flash.now[:error] = "Credentials were wrong."
            render :new
        else
            login!(user)
            # render json: "Welcome back #{user.username}!"
            redirect_to user_path(user)
        end
    end

    def destroy
        logout!
        redirect_to new_session_path
    end

    # private

    # def session_params
    #     self.params.require(:user).permit(:username, :password)
    # end


end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
    def index
        render json: Cat.find(params[:cat_id]).toys
    end

    def show
        @cat = Toy.find(self.params[:id])
        render :show
    end

    def create
        # catid = Cat.find(params[:toy][:cat_id]).id
        @toy = Toy.new(toy_params)
        # @catid = self.params[:cat_id]
        @cat = Cat.find(params[:toy][:cat_id])

        if @toy.save
            redirect_to cat_url(@cat)
        else
            # render :new
            render :new
        end
    end

    def new
        @cat = Cat.find(params[:cat_id])
        @toy = Toy.new
        render :new
    end

    def edit

    end

    def destroy
        toy = Toy.find(params[:id])
        toy.destroy
        render json: toy
    end

    def update
        toy = Toy.find(params[:id])
        if toy.update(toy_params) 
            render json: toy
        else
            render json: toy.errors.full_messages, status: :unprocessable_entity
        end
    end

    private
    
    def toy_params
        self.params[:toy].permit(:name, :style, :cat_id, :find_cat_id)
    end

    def find_cat_id
        Cat.find(params[:toy][:cat_id]).id
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_current_user!, except: [:create, :new]

    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to user_path(@user)
        else
            # render json: @user.errors.full_messages
            flash.now[:error] = "User exists or password is less than 6 digits!"
            # redirect_to new_user_path
            render :new
        end
    end

    def new 
        @user = User.new
        render :new
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end


    private

    def user_params
        self.params.require(:user).permit(:username, :password)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cats/_form.html.erb
<% action_form = cat.persisted? ? cat_path(cat) : cats_url %>
<% method_form = cat.persisted? ? "PATCH" : "POST" %>
<% submit_value = cat.persisted? ? "Update Cat!" : "Create Cat!" %>


<form action="<%= action_form %>" method="POST">
    <input type="hidden" name="_method" value=<%= method_form %>>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <lable for="cat_name">Cat Name</lable><br>
    <input type="text" 
           name="cat[name]"
           id="cat_name"
           value="<%= @cat.name %>">
    <br>
    <br>
    <lable for="cat_gender">Cat Gender</lable><br>
    <input type="text" 
           name="cat[gender]" 
           id="cat_gender" 
           placeholder="female or male"
           value="<%= @cat.gender %>">
    <br>
    <br>
    <input type="submit" value=<%= submit_value %>>
</form>
<br>
<br>
<a href=" <%= cats_url %> ">Back to all cats!</a>

<!-- equivalent to the above: <%#= link_to 'Back to all cats!', cats_url %> -->

app/views/cats/edit.html.erb
<h1>Update <%= @cat.name %>!</h1>

<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<h1>All the cats!</h1>

<ul>
    <% @cats.each do |cat| %>
        <li style="color:Tomato;">
            <a href="<%= cat_url(cat.id) %>">
                <%= cat.name %>
            </a>
            <br>
            <br>
            <form action="<%= cat_url(cat) %>" method="POST">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="submit" value="Delete <%= cat.name %>">
            </form>
            <br>
        </li>
    <% end %>
    <br>
    <li>Cats would be listed here.</li>
    <li>This would be another cat.</li>
</ul>

<a href="<%= new_cat_url %>">Create a new cat</a>

app/views/cats/new.html.erb
<h1>Build a new cat!</h1>

<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<pre><%= @cat.to_json %></pre>

<p><%= @cat.name %> has toys as below:</p>

<ul>
    <% @cat.toys.each do |toy| %>
        <li><%= toy.name %></li>
    <% end %>
</ul>

<a href=" <%= new_cat_toy_url(@cat) %> ">Create a new toy</a>
<br>
<br>

<a href=" <%= edit_cat_url %> ">Edit this cat!</a>
<br>
<br>

<a href=" <%= cats_url %> ">Back to all cats!</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if !current_user.nil? %>
      <ul>
        <li>Logged in as: <%= current_user.username %></li>
        <li>
          <form action="<%= session_path %>" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" value="Logout">
          </form>
        </li>
      </ul>
    <% else %>
      <%= link_to "Sign up!", new_user_path %> or 
      <%= link_to "Sign in!", new_session_path %>
    <% end %>

    <%= yield %>
  </body>

  <footer>
    <%= link_to "See all cats!", cats_path %>
    <p>This is a CatApi property.</p>
    <%= yield :footer %>
  </footer>
</html>

app/views/toys/new.html.erb
<h1><%= @cat.name %>'s New Toy</h1>

<form action="/toys" method="POST">
    <input type="hidden" name="toy[cat_id]" value="<%= @cat.id %>">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="toy_name">Toy Name</label><br>
    <input id="toy_name" type="text" name="toy[name]" value="<%= @toy.name %>">
    <br>
    <br>

    <label for="toy_style">Toy Style</label>
    <select id="toy_style" name="toy[style]">
        <% Toy::STYLES.each do |style| %>
            <option value="<%= style %>" 
                <%= "selected" if @toy.style == style %>> <%= style.upcase %> 
            </option>
        <% end %>
    </select>

    <input type="submit" value="Create Toy!">
</form>

<br>
<a href=" <%= cats_url %> ">Back to all cats!</a>

app/views/toys/show.html.erb
<h1><%= @toy.name %></h1>

<pre><%= @toy.to_json %></pre>

<p><%= @toy.name %> belongs to the cat:<%= @toy.cat %></p>


<a href=" <%= cats_url %> ">Back to all cats!</a>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_path(user) : users_path) %>
<% method = (user.persisted? ? "PATCH" : "POST") %>
<% button_text = (user.persisted? ? "Update User!" : "Create User!") %>

<form action="<%= action %>", method="POST">
    <input type="hidden" name="_method" value="<%= method %>" >
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

    <label for="user_name">Username</label>
    <input id="user_name" name="user[username]" type="text" value="<%= @user.username %>">
    <br><br>

    <label for="user_password">Password</label>
    <input id="user_password" name="user[password]" type="password">
    <br><br>

    <input type="submit" value="<%= button_text %>">
</form>

app/views/users/new.html.erb
<h1>Create user!</h1>

<h4><%= flash.now[:error] %>
<br>
<br>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>

<p>Current Counter Value: <%= @user.counter %></p>

<form action="<%= user_counter_path(@user) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="user_counter">New Counter</label>
    <input id="user_counter" type="number" name="user[user_id][counter]">

    <input type="submit" value="Update Counter!">
</form>